core:
  server:
    name: "Stock Foundamental Analysis"
    version: ""
    description: ""
    app_module: "main:app"
    host: "0.0.0.0"
    port: 5005
    prefix: "/stock-foundamental-analysis"
  auth:
    xapikey: "example-apy-key"
  log_level: "DEBUG"
  cog_skills:
    errors_in_warnings: true

gateways:

